/*
===============================================================================
Project      : Enterprise E-commerce Analytics
Author       : Rudra Save
Database     : PostgreSQL
File         : 01_sales_analysis.sql

Purpose:
Analyze overall sales performance, revenue trends,
top-performing products, categories, cities, and states.

===============================================================================
*/

-- ============================================================================
-- QUESTION 1
-- Total Revenue
-- Business Value:
-- Understand the total revenue generated by the platform.
-- ============================================================================

SELECT
    ROUND(SUM(price),2) AS total_revenue
FROM analytics.sales_summary;


-- ============================================================================
-- QUESTION 2
-- Total Number of Orders
-- Business Value:
-- Measure total customer orders.
-- ============================================================================

SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM analytics.sales_summary;


-- ============================================================================
-- QUESTION 3
-- Average Order Value
-- Business Value:
-- Determine how much customers spend on average.
-- ============================================================================

SELECT
    ROUND(
        SUM(price) /
        COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM analytics.sales_summary;


-- ============================================================================
-- QUESTION 4
-- Monthly Revenue Trend
-- Business Value:
-- Analyze seasonality and business growth.
-- ============================================================================

SELECT

    DATE_TRUNC('month', order_purchase_timestamp) AS month,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY month

ORDER BY month;


-- ============================================================================
-- QUESTION 5
-- Top 10 Product Categories by Revenue
-- Business Value:
-- Identify the highest earning categories.
-- ============================================================================

SELECT

    product_category_name,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY product_category_name

ORDER BY revenue DESC

LIMIT 10;


-- ============================================================================
-- QUESTION 6
-- Top 10 Sellers by Revenue
-- Business Value:
-- Evaluate seller performance.
-- ============================================================================

SELECT

    seller_id,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY seller_id

ORDER BY revenue DESC

LIMIT 10;


-- ============================================================================
-- QUESTION 7
-- Top 10 Cities by Revenue
-- Business Value:
-- Identify strongest markets.
-- ============================================================================

SELECT

    customer_city,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY customer_city

ORDER BY revenue DESC

LIMIT 10;


-- ============================================================================
-- QUESTION 8
-- Revenue by State
-- Business Value:
-- Compare sales performance across states.
-- ============================================================================

SELECT

    customer_state,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY customer_state

ORDER BY revenue DESC;


-- ============================================================================
-- QUESTION 9
-- Average Product Price by Category
-- Business Value:
-- Compare pricing across categories.
-- ============================================================================

SELECT

    product_category_name,

    ROUND(AVG(price),2) AS average_price

FROM analytics.sales_summary

GROUP BY product_category_name

ORDER BY average_price DESC;


-- ============================================================================
-- QUESTION 10
-- Daily Revenue Trend
-- Business Value:
-- Monitor day-to-day sales performance.
-- ============================================================================

SELECT

    DATE(order_purchase_timestamp) AS sales_date,

    ROUND(SUM(price),2) AS revenue

FROM analytics.sales_summary

GROUP BY sales_date

ORDER BY sales_date;